### ISSUE TITLE
DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.

### ISSUE THREAD

**Issue by adriatic** [gooy/aurelia-markdown#3]
This is the code that creates the exception
```html
<markdown>
            ```
            <input au-kendo-autocomplete="data-source.bind: datasource;
                                data-text-field: ProductName;
                                filter: contains;
                                min-length: 3" value.bind="value" style="width: 300px"></input>
            ```
          </markdown>
```

The generated output is:
```html
<input au-kendo-autocomplete="data-source.bind: datasource;
                    data-text-field: ProductName;
                    filter: contains;
                    min-length: 3" value.bind="value" style="width: 300px">
```

**Note the missing `</input>`**

**Here is the stack trace**
```
DEBUG [templating] importing resources for http://localhost:3000/src/autocomplete/remote-data.html ["gooy/aurelia-markdown"]
aurelia-templating.js:3892 The @skipContentProcessing decorator is deprecated and will be removed in a future release. Please use @processContent(false) instead.
jquery.js:5562 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
aurelia-logging-console.js:62 ERROR [app-router] DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at Error (native)
    at Markdown.valueChanged (http://localhost:3000/jspm_packages/github/gooy/aurelia-markdown@0.0.3/markdown.js:65:28)
    at Markdown.attached (http://localhost:3000/jspm_packages/github/gooy/aurelia-markdown@0.0.3/markdown.js:40:16)
    at BehaviorInstance.attached (http://localhost:3000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2539:29)
    at View.attached (http://localhost:3000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:959:22)
    at View.attached (http://localhost:3000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:964:21)
    at ViewSlot.attached (http://localhost:3000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:1349:15)
    at View.attached (http://localhost:3000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:964:21)
    at ViewSlot.add (http://localhost:3000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:1207:14)
    at RouterView.swap (http://localhost:3000/jspm_packages/github/aurelia/templating-router@0.16.1/router-view.js:68:21)error @ aurelia-logging-console.js:62log @ aurelia-logging.js:56error @ aurelia-logging.js:89processResult @ aurelia-router.js:1726(anonymous function) @ aurelia-router.js:1582run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
aurelia-logging-console.js:62 ERROR [app-router] Router navigation failed, and no previous location could be restored.
```

**Comment by adriatic** [comment]
Apologies - this was a false alarm, as I failed to understand that markdown custom element would not see this

```html
<markdown>
            ```
            <input au-kendo-autocomplete="data-source.bind: datasource;
                                data-text-field: ProductName;
                                filter: contains;
                                min-length: 3" value.bind="value" style="width: 300px"></input>
            ```
</markdown>
```
bur rather the inner html (browser would strip `<input` tag). Luckily, Charles Pockert thought of a nice trick to hide the html code we wanted markdown to process (echo to the output) in a `textarea` element
